version: "3.9"

services:
  backend:
    image: python_fastapi
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    depends_on:
      - database
    ports:
      - 50082:8000

  frontend:
    image: js
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      NODE_ENV: development
    ports:
      - 50081:8000

  database:
    image: database
    build: 
      dockerfile: Dockerfile
      context: ./database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=data
    
  proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - 50080:80
    depends_on:
      - database
      - frontend
      - backend
